//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserMail { get; set; }
        public string UserPassword { get; set; }

    }
}
